# Generated by Django 4.2.9 on 2024-07-20 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skill_cards',
            options={'verbose_name_plural': 'Skill Cards'},
        ),
        migrations.AddField(
            model_name='skill_cards',
            name='image_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
