# Generated by Django 4.2.9 on 2024-07-20 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_skill_cards_options_skill_cards_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='current_projects',
            name='image_url',
            field=models.URLField(blank=True, max_length=1028, null=True),
        ),
        migrations.AlterField(
            model_name='offerings',
            name='name',
            field=models.CharField(max_length=40),
        ),
    ]
